### ISSUE TITLE
feat: yarn instead of npm

### ISSUE THREAD

**Issue by viceice** [renovatebot/presets#100]
Can we switch to yarn instead of npm for package references?

**Comment by rarkins** [comment]
Can you give an example?

**Comment by viceice** [comment]
i would simply use `yarn import` to generate a `yarn.lock` from `package-lock.json`. 
Then remove `package-lock.json` and change `.travis.yml` to use `yarn` instead of `npm run`.

I can send a pr.

**Comment by viceice** [comment]
Done

**Comment by rarkins** [comment]
Any advantage apart from consistency across main repo and here?

**Comment by viceice** [comment]
In our daily work yarn is mostly faster then npm.

**Comment by rarkins** [comment]
Ok, I’ll be able to review later today when back to computer. Thanks
