### ISSUE TITLE
graphql-code-generator does not pick up packages from monorepo correctly

### ISSUE THREAD

**Issue by SimenB** [renovatebot/presets#104]
Current entry:

```json
    "graphqlcodegenerator": {
      "description": "graphqlcodegenerator monorepo",
      "packageNames": [
        "graphql-code-generator",
        "graphql-codegen-core"
      ]
    },
 ```

It only picks up the 2 packages from the top level of `packages`, not the ones in `packages/*/*/package.json` (like all the packages in https://github.com/dotansimha/graphql-code-generator/tree/master/packages/plugins)

The entry was added in #45.

I tried to put together a PR, but I'm not sure how to provide pattern it should glob? Looking at the code, it seems I can just provide a single string `path`

**Comment by rarkins** [comment]
Thanks for the heads-up. I'll take a look and fix it.

**Comment by SimenB** [comment]
Woah, that was quick. Thanks!

**Comment by rarkins** [comment]
I've switched this package to use sourceUrlPrefixes rather than a list of package names. That way the matching/grouping is done dynamically by Renovate at runtime and any npm package that reports its source repo as dotansimha/graphql-code-generator will be grouped. Do you have any public repo you were testing this on that we can use to verify it's working as intended?

**Comment by SimenB** [comment]
It's a private repo, unfortunately

**Comment by rarkins** [comment]
If you have any open PR right now and check the rebase checkbox, Renovate should run again on that repo and pick up the preset changes.

**Comment by SimenB** [comment]
I closed the PRs, tried renaming one of the closed ones now like it told me to. Will report back 🙂

**Comment by rarkins** [comment]
Actually just doing the rebase checkbox is probably easiest in future, as it should have been able to reuse the existing branch/PR. FYI when you ask to rebase any PR, Renovate actually runs on the entire repository to pick up changes, so it's more like a "rebase this PR and also check the entire repository for changes while you're at it" box.

**Comment by SimenB** [comment]
Ah, ok. It doesn't seem to have worked though

![image](https://user-images.githubusercontent.com/1404810/53869763-231cb000-3ff9-11e9-8376-cb0e7e922dc1.png)

Was opened 10:09 (less than 10 minutes ago) not sure if the changes have been picked up?

**Comment by rarkins** [comment]
It's possibly still cached. I'll test it out myself to be sure.

**Comment by SimenB** [comment]
I ticked the rety box in it, still only changed that single package

**Comment by rarkins** [comment]
I have partially reproduced. It seems that at least one of the packages is reporting a legacy repo source (https://github.com/dotansimha/graphql-codegen) in its `package.json`, which I can fix by adding an additional source url prefix to the presets.

**Comment by rarkins** [comment]
Should now be fixed, example here: https://github.com/renovate-tests/test-graphql-gen/pull/4

**Comment by SimenB** [comment]
I ticked `retry` and it just closed the PR?

![image](https://user-images.githubusercontent.com/1404810/53871628-e94da880-3ffc-11e9-81ed-eb38f2838e29.png)

**Comment by rarkins** [comment]
Once they get grouped together, it's all under one branch. So any existing branches/PRs that had the wrong branch previously will be autoclosed.

Also, if you are using the default settings then Renovate limits itself to creating two PRs per hour maximum, so it's possible the replacement is rate limited. However if you had the monorepo PR already open, please refresh it as it should be updated.

**Comment by SimenB** [comment]
Alright, thanks! Will report back in a few hours then 🙂

**Comment by rarkins** [comment]
By the way, if you add `"masterIssue": true` to your config, you will see a convenient Issue created that gives you full visibility about Renovate's PRs - open, closed, and pending. You can see [this example in Renovate's repo](https://togithub.com/renovatebot/renovate/issues/2958).

**Comment by SimenB** [comment]
Oh, that's awesome! Will add

**Comment by SimenB** [comment]
While the master issue didn't immediately pop up, the codegen PR showed up correct now 🙂 

![image](https://user-images.githubusercontent.com/1404810/53873648-169c5580-4001-11e9-8bef-d537c4971b88.png)

I'd change the name from `graphqlcodegenerator` to `graphql-code-generator`, but it works 🎉

**Comment by rarkins** [comment]
Just to clarify: in the Renovate repo I'm actually using `"masterIssue Approval": true` to test that feature out. It actually holds back all PRs until you manually check/approve them. The basic `masterIssue` doesn't change any of the flow - it is just like a mini dashboard within the repo.

**Comment by SimenB** [comment]
The master issue showed up as well now - it's awesome!
