### ISSUE TITLE
Configure different emoji depending on commitMessageAction

### ISSUE THREAD

**Issue by Roms1383** [renovatebot/presets#122]
### Which Renovate are you using? CLI, App, or Pro

Looking forward to use Renovate App, but not yet merged the first PR.

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps

GitHub organization with public repositories in becoming.

### Have you checked the logs? Don't forget to include them if relevant

Not yet, as I haven't installed it yet.

### Context

So, I'm currently creating a [Yeoman](https://yeoman.io) opinionated project to handle scaffolding and syncing config files, carrying redundant tasks on my behalf across all the future repositories.

I first wired [Greenkeeper](https://greenkeeper.io) to benefit from dependencies PR updates, but looking at your project it looks very interesting.

I planned to use Travis and Renovate to build CI/CD automation.

### What is your question?

I currently use [Gitmoji](https://gitmoji.carloscuesta.me/) based semantic release, which I enjoy a lot more than classic semantic conventions.

To be able to do so, I use [semantic-release](https://github.com/semantic-release/semantic-release) / [semantic-release-gitmoji](https://github.com/momocow/semantic-release-gitmoji) / [commitlint](https://github.com/conventional-changelog/commitlint) / [commitlint-config-gitmoji](https://github.com/arvinxx/commitlint-config-gitmoji) / some other projects on top of which I setup custom configurations.

Sample can be found [here](https://github.com/silver-path/generator-trod), README isn't complete yet though.

All my automated semantic releases rely on a commit template like so : 
```
:emoji: Some title

Facultative message body

Facultative extras like : #1
```

Finally my question is easy : can I for example setup `commitMessagePrefix` depending on `commitMessageAction` that : 
*  `Update` add `:arrow_up:` prefix to the title
*  `Pin` add `:pushpin:` prefix to the title
*  `Roll back` add `:arrow_down:` prefix to the title
... and so on ?

Thanks in advance ^^

**Comment by Roms1383** [comment]
> I think that the three you originally suggested (normal = arrow up, pin = pin, and rollback = arrow down) work well and we could add that as a "gitmoji" preset.

Actually from what I understood so far :
* `major`, `minor`, `patch` = `:arrow_up:`
* `pin`, `lockFileMaintenance` = `:pushpin:`

The ones I'm not so sure : 
* `digest` = if it's setting Docker release to a specific digest I would probably suggest `:bookmark:` (if considered as tagging / releasing)
* `bump` = as I understood from your comment, this one should never happen, but if somebody enables it, then I would probably suggest `:bookmark:` (if considered as tagging / releasing)

That would be nice having @carloscuesta joins the discussion and gives his own opinion on the matter.

**Comment by rarkins** [comment]
I would lean towards `:arrow_up:` for nearly all of them, including lockFileMaintenance, digest and bump. All three of those are upgrading dependencies one way or another.

**Comment by Roms1383** [comment]
Conceptually `:arrow_up:` is when upgrading dependencies (to an upper version), whereas `:pushpin:` is pinning dependencies to specific versions. `:bookmark:` brings the notion of releasing or tagging. One thing to keep in mind too is that, for those who choose to automatically bump the version in `package.json` (as we used to in my former company), we for example associated the `:bookmark:`  with the process, especially since it shouldn't trigger another `semantic-release` of any sort (otherwise you end up in an infinite loop of releases, as a release will trigger another release and so on).

**Comment by Roms1383** [comment]
When applying this `.renovaterc` :
```json
{
  "timezone": "Asia/Bangkok",
  "schedule": [
    "every weekend"
  ],
  "packageRules": [
    {
      "semanticCommitType": ":arrow_up:",
      "semanticCommitScope": null
    },
    {
      "updateTypes": [
        "lockFileMaintenance",
        "pin"
      ],
      "semanticCommitType": ":pushpin:"
    },
    {
      "updateTypes": [
        "rollback"
      ],
      "semanticCommitType": ":arrow_down:"
    },
    {
      "updateTypes": [
        "digest",
        "bump"
      ],
      "semanticCommitType": ":bookmark:"
    }
  ]
}
```
I ended up having this issue created by renovate bot :
<img width="1048" alt="Screen Shot 2562-05-26 at 19 18 52" src="https://user-images.githubusercontent.com/21016014/58381751-3a14e200-7feb-11e9-958a-c9f639f40741.png">

What did I do wrong here ?

**Comment by rarkins** [comment]
You need a selector in the first rule. Eg `packagePatterns: [“*”]`

**Comment by rarkins** [comment]
Also as mentioned, you don't need it in a rule:

```
{
  "timezone": "Asia/Bangkok",
  "schedule": [
    "every weekend"
  ],
  "semanticCommitType": ":arrow_up:",
  "semanticCommitScope": null,
  "packageRules": [
    {
      "updateTypes": [
        "lockFileMaintenance",
        "pin"
      ],
      "semanticCommitType": ":pushpin:"
    },
    {
      "updateTypes": [
        "rollback"
      ],
      "semanticCommitType": ":arrow_down:"
    },
    {
      "updateTypes": [
        "digest",
        "bump"
      ],
      "semanticCommitType": ":bookmark:"
    }
  ]
}
```

**Comment by Roms1383** [comment]
Works like a charm!
