### ISSUE TITLE
automergeType allowed values

### ISSUE THREAD

**Issue by tanoabeleyra** [renovatebot/presets#123]
Hi,

I just started using Renovate and the doc about the allowed types for [automergeType](https://renovatebot.com/docs/configuration-options/#automergetype) is a bit confusing. It says that the allowed values are: `branch,pr,pr-comment`, but the preset uses two other values:

- [branch-merge-commit](https://github.com/renovatebot/presets/blob/master/packages/renovate-config-default/package.json#L288)
- [branch-push](https://github.com/renovatebot/presets/blob/master/packages/renovate-config-default/package.json#L292)

Are those values outdated?, how do they work?

**Comment by rarkins** [comment]
Those values are outdated, actually. We previously had two different ways to branch automerge but changed it to one. They should be changed to just point to value `branch` and one day deprecated.

**Comment by tanoabeleyra** [comment]
So, both presets `automergeBranchMergeCommit` and `automergeBranchPush` will currently work as if `automergeType="branch"`?

**Comment by rarkins** [comment]
Yeah, we have some code to "massage" them both to "branch". You should ideally just use "branch" now though. By the way, I also thought the existing documentation for `automergeType` was confusing so I rewrote it just now. The new description should be live within 5 minutes

**Comment by tanoabeleyra** [comment]
Nice!, thank you for the quick response and congratulations for such a great product.

**Comment by rarkins** [comment]
Thanks, I hope you enjoy using it
