### ISSUE TITLE
Action Required: Fix Renovate Configuration

### ISSUE THREAD

**Issue by simoneb** [renovatebot/presets#131]
I just received this issue from renovate on one repo where I have it enabled:

```
There is an error with this repository's Renovate configuration that needs to be fixed. As a precaution, Renovate will stop PRs until it is resolved.

Error type: Preset name not found within published preset config (monorepo:babel6). Note: this is a nested preset so please contact the preset author if you are unable to fix it yourself.
```

I don't have any custom preset configuration in my config, so I assume that something broke in Renovate presets. Any idea?

**Comment by simoneb** [comment]
Indeed it's been caused by this: https://github.com/renovatebot/presets/commit/ab6976ca3860d9cdb156f225f9951cb1540f01a3#diff-99f2e4c80f455c7574d9f5b373cf4ec9. monorepo:babel6 disappeared, but we're not using it in our config anyway.

**Comment by rarkins** [comment]
Sorry for that, it should resolve itself but I'll add a workaround too just in case.

**Comment by simoneb** [comment]
Thanks

**Comment by simoneb** [comment]
@rarkins how do we know when it's fixed? there's nothing telling us whether renovate is working or not, and the issue it opened is still there

**Comment by simoneb** [comment]
@rarkins UPDATE: it actually got closed automatically now

**Comment by rarkins** [comment]
Thanks for confirming - that was the expected behaviour
