### ISSUE TITLE
Arcus monorepo not respected

### ISSUE THREAD

**Issue by tomkerkhove** [renovatebot/presets#183]
With #181 I've introduced mono repos for Arcus but it turns out I've probably misconfigured them given they are not respected.

Based on https://github.com/renovatebot/presets/blob/master/packages/renovate-config-monorepo/generate.js#L12 I would expect all of the packages from there to be updated in parallel.

However, multiple of them are opened:
![image](https://user-images.githubusercontent.com/4345663/75788215-35ded780-5d68-11ea-9889-2f7af1ea0fc9.png)

We don't use that extensive configuration : https://github.com/arcus-azure/arcus.templates/blob/master/renovate.json#L10

/cc @stijnmoreels

**Comment by rarkins** [comment]
Sorry, it hasn't been published yet. Automatically publishing is still on the todo list.

**Comment by tomkerkhove** [comment]
No worries, just wanted to verify if I did something wrong!

Looks like it's working now, thanks!
