### ISSUE TITLE
Does anything need to be done on my end to receive the updated monorepo presets?

### ISSUE THREAD

**Issue by tom-sherman** [renovatebot/presets#208]
A PR of mine was merged to add Reakit to the list of monorepos but I'm still getting seperate PRs for those packages. Do I need to update the bot my end to receive these updates?

**Comment by rarkins** [comment]
All presets were moved into the main repo and should be active already. 


https://github.com/renovatebot/renovate/blob/e1b4b7f6c220956a557d3decc361b31df9f9482f/lib/config/presets/internal/monorepo.ts#L94

If not working, maybe the packages don’t correctly specify their source repo?

**Comment by tom-sherman** [comment]
They look to be configured correctly:

https://github.com/reakit/reakit/blob/master/packages/reakit-test-utils/package.json#L6

https://www.npmjs.com/package/reakit-utils

https://github.com/reakit/reakit/blob/master/packages/reakit-test-utils/package.json#L6

https://www.npmjs.com/package/reakit-test-utils

MRs for these on from a self hosted version of the renovate bot were opened on our Gitlab instance yesterday.

**Comment by rarkins** [comment]
Can you create a small reproduction in a public github.com repo? e.g. a package.json with two outdated reakit dependencies, such that you would expect them to be upgraded in the same PR?

**Comment by tom-sherman** [comment]
Just set it up on a test repo (amazing setup UX by the way, took literally 30 seconds), and a PR has been opened with both packages included: https://github.com/tom-sherman/renovate-reakit-monorepo-issue/pull/2

Could there be some different behaviour going on in our self hosted version?

**Comment by viceice** [comment]
@tom-sherman which version of renovate do you use?

**Comment by tom-sherman** [comment]
19.114.0, we're now gonna update to see if that fixes it.

**Comment by tom-sherman** [comment]
Updating to the most recent version has fixed it, renovate auto-closed the the two MRs and reopened a MR to update the reakit monorepo. Thanks for your help!

Is pulling them in at runtime a recent addition? In any case, we've added a cron job to update the bot to the latest version each night.

**Comment by viceice** [comment]
Yes, we added them to be buildin recently, so you have to update renovate to get latest changes now
