### ISSUE TITLE
Private NPM packages showing warnings in on boarding PR 

### ISSUE THREAD

**Issue by timReynolds** [renovatebot/presets#24]
I've tried to add an NPM token following the instructions ["Add an encrypted npm token to repository"](https://renovateapp.com/docs/deep-dives/private-modules) however my onboarding PR is still giving me warnings about private packages e.g. `@trussle/package-name`. 

Is this incorrectly configured or does the onboarding PR not clear these warnings? I've tried issuing other tokens and using the encode the .npmrc file options also, but still see the warning message in the onboarding PR. 

**_renovate.json_**
```json
{
  "extends": ["config:base"],
  "minor": {
    "groupName": "minor"
  },
  "docker": { "enabled": false },
  "encrypted": {
  "npmToken":  ""
  }
}
```

**Comment by rarkins** [comment]
Assuming you're using private modules at the regular npmjs registry, then it's simplest to just configure the `npmToken` like you're doing. I'll take a look at the logs. Is the repo name three letters and starting with `b` ?

**Comment by rarkins** [comment]
I can see in the logs that it's being successfully decrypted:
```
{"config":{"npmToken":"***********"},"msg":"Found encrypted config","time":"2018-03-27T14:05:14.556Z"}
{"msg":"Decrypted npmToken","time":"2018-03-27T14:05:14.558Z"}
{"msg":"Migrating npmToken to npmrc","time":"2018-03-27T14:05:14.558Z"}
```

But I also see:
```
{"msg":"GET repos/******/***/contents/.npmrc?ref=renovate/configure [retries=5]","time":"2018-03-27T14:05:15.174Z"}
{"packageFile":"package.json","msg":"Found .npmrc","time":"2018-03-27T14:05:15.335Z"}
```

This implies that there is an `.npmrc` file checked into the repository, which would override the configured one you have.

If so, please add the config `"ignoreNpmrc": true` to your `renovate.json` and see if it changes the result. That setting tells Renovate to ignore any `.npmrc` in the repo.

**Comment by timReynolds** [comment]
@rarkins Thanks for looking into this, that is probably the issue as that .npmrc file just has some configuration and not a token in it. Will try you suggestion and see what happens. 

All the help is much appreciated.

**Comment by rarkins** [comment]
FYI, I am going to make a code change to Renovate so that it automatically ignores any `.npmrc` in the repository if the user has configured one manually (i.e. like you've done). I think it's unintuitive otherwise.

**Comment by timReynolds** [comment]
Updating the config resolved the issue. 

Changing the default behavior would have helped us but it's hard for me to know the impact for everyone. 

Having more information in the documentation would have been enough to help me resolve this myself. 

Again thanks for all the help
