### ISSUE TITLE
Add Monorepo accounts

### ISSUE THREAD

**Issue by jycouet** [renovatebot/presets#27]
Hi, 

Here is a mono repo that I'm using: https://github.com/accounts-js/accounts

How should I config the monorepo in my `renovate.json` config?
How could I add this directly in your preset so that everyone benefit from the config?

Thx

**Comment by rarkins** [comment]
They can be added here: https://github.com/renovateapp/renovate-config/tree/master/packages/renovate-config-monorepo

**Comment by rarkins** [comment]
Specifically, to the dynamic sources section as it is using `lerna`: https://github.com/renovateapp/renovate-config/blob/master/packages/renovate-config-monorepo/generate.js#L49
