### ISSUE TITLE
Micro package preset

### ISSUE THREAD

**Issue by Siilwyn** [renovatebot/presets#4]
Based on our [earlier discussion](https://github.com/singapore/renovate/issues/901). :)

I'd like to put up a config preset for small focused package, aka [micro packages](https://github.com/parro-it/awesome-micro-npm-packages). What defines these packages is that they don't need much maintenance and only have a few dependencies. This translates to no version pinning, grouping of all dependencies and a monthly schedule:
```
{
  "pinVersions": false,
  "groupName": "all",
  "schedule": ["before 8am on the first day of the month"],
  "lockFileMaintenance": {
    "schedule": ["before 8am on the first day of the month"]
  }
}
```

Instead of opening a PR I'm opening this issue because I'm not sure where to put such a config in the current directory structure. Correct me if I'm wrong, no directory/category seems to fit the above unless split.

**Comment by rarkins** [comment]
@Siilwyn thanks for the suggestion

I'll create this as a PR soon and let you know.

**Comment by rarkins** [comment]
I've published this idea it into a new package called `renovate-config-config`. I decided to name your config `semverAllMonthly` because I don't think we can say that 100% of micro package authors would necessarily agree. You should then be able to configure your micro packages config as following:

```json
{
  "extends": ["config:semverAllMonthly"]
}
```

Here is the definition of it:
```json
    "semverAllMonthly": {
      "description": "Preserve semver ranges and update everything together once a month",
      "extends": [
        ":preserveSemverRanges",
        ":group(all)",
        "schedule:monthly",
        ":maintainLockFilesMonthly"
      ]
    }
```
