### ISSUE TITLE
RENOVATE_NPMRC

### ISSUE THREAD

**Issue by ghost** [renovatebot/presets#42]
A follow up to https://github.com/renovatebot/pro/issues/11

I am setting `RENOVATE_NPMRC` to `registry=http://artifactory.example.com/artifactory/api/npm/npm/\n@scope:registry=http://artifactory.example.com/artifactory/api/npm/npm-scope/`

Renovate seems to get the `registry` configuration value correctly, but the `@scope:registry` property is not set. Therefore, all requests for `@scope` packages are failing.

I thought, based on another issue I saw, that the newline would allow Renovate to correctly re-create the `.npmrc` file when it contains two more or more lines.

**Comment by rarkins** [comment]
@destroyerofbuilds I will try to reproduce this and fix it, if applicable. Maybe the `\n` is being escaped to `\\n` before it reaches our code and we need to add a simple search/replace.

**Comment by rarkins** [comment]
Should be fixed in renovate@12.11.1: https://github.com/renovateapp/renovate/releases/tag/12.11.1

I will publish that to Renovate Pro latest soon too.

**Comment by ghost** [comment]
Thank you @rarkins! I've confirmed the `latest` Docker image is working as desired.
