### ISSUE TITLE
@fortawesome group

### ISSUE THREAD

**Issue by jfairley** [renovatebot/presets#46]
I'd like to configure my repos to update `@fortawesome` dependencies in bulk, but I'm struggling to understand how to make it happen. Can someone show me how this is supposed to work?

My dependencies are:

```
"@fortawesome/angular-fontawesome": "0.1.0-7",
"@fortawesome/fontawesome-free-brands": "5.0.10",
"@fortawesome/fontawesome-pro-light": "5.0.10",
"@fortawesome/fontawesome-pro-regular": "5.0.10",
"@fortawesome/fontawesome-pro-solid": "5.0.10",
"@fortawesome/fontawesome-svg-core": "1.2.0-11",
```

Thanks!

**Comment by jfairley** [comment]
I'm also interested in grouping webpack and webpack loaders. Should I make a separate issue to ask for help with that?

**Comment by rarkins** [comment]
Are fortawesome from a common monorepo? Or identified by @fortawesome/* ?

I don’t want to make any rule that’s “select fortawesome packages that jfairley uses” but it’s fine if it’s like the others and from a common repo or covering everything they release. 

For webpack, raise a separate issue for that so we can decide what’s best

**Comment by jfairley** [comment]
@rarkins, Oh I was expecting to have to set it up in my custom `renovate.json`.

AFAIK, it's not a monorepo. In fact, it seems that they're not even all public repos.
https://github.com/FortAwesome shows the angular repo I'm using, but the others I don't see (probably because they're private).

**Comment by jfairley** [comment]
It'd be awesome if I could say in my `renovate.json`, "anything in this array" or "anything that matches this regex" should be bulk updated.

**Comment by rarkins** [comment]
Oh ok, this is actually the repo for shared presets. Can you raise in renovatebot/config-help instead? Anything in your own Renovate config is fine of course :)

**Comment by jfairley** [comment]
Ah. I didn't see that repo. Someone else's config for `@types` is probably exactly what I want to do.

https://github.com/renovatebot/config-help/issues/25

Thanks!

**Comment by rarkins** [comment]
Feel free to post your config there anyway, happy to help

**Comment by jfairley** [comment]
https://github.com/renovatebot/config-help/issues/38
