### ISSUE TITLE
Prod dependencies unexpectedly pinned

### ISSUE THREAD

**Issue by ryasmi** [renovatebot/presets#56]
Hey, I've just noticed that [the production dependencies got pinned](https://github.com/HT2-Labs/jscommons/commit/e1591c67df2eb027d1f39006c831257082725286) for some of our repos.

The [renovate config for one of those repositories](https://github.com/HT2-Labs/jscommons/blob/master/renovate.json) is:

```json
{
  "extends": [
    "@ht2-labs:base"
  ]
}
```

That config extends [our base config](https://github.com/HT2-Labs/renovate-config/blob/master/package.json#L14-L25) which is this:

```json
{
  "extends": [
    ":library"
  ],
  "automerge": true,
  "automergeType": "branch-push",
  "major": {
    "automerge": false
  }
}
```

I've noticed that [the `:library` config](https://github.com/renovatebot/presets/blob/master/packages/renovate-config-default/package.json#L459-L465) appears to be deprecated in here, so I'm guessing I need to change to [the `config:js-lib` config](https://github.com/renovatebot/presets/blob/master/packages/renovate-config-config/package.json#L50-L56), however, the `:library` config does currently extend the `config:js-lib` so I'm not sure if that's going to work. I will try that anyway when I get a minute, I think I'll also need to manually unpin the pinned prod dependencies so it might take a little while.

**Comment by rarkins** [comment]
Hi Ryan, sorry for the inconvenience here.

I changed some terminology in how to specify range behaviour recently although it was not intended that existing repositories should experience changes to behaviour.

The app's default behaviour should remain as "don't pin", but as you are chaining some presets, that might be where the difference is coming from. Obviously we don't want dependencies to be pinned for a library anyway, so I'll look into it now.

**Comment by rarkins** [comment]
Unfortunately the automerging pinning has come back again. I have raised https://github.com/HT2-Labs/renovate-config/pull/1 as an explicit workaround for your base config for now.

**Comment by rarkins** [comment]
Here's your preset:
```
  "renovate-config": {
    "base": {
      "extends": [
        "config:js-lib"
      ],
      "automerge": true,
      "automergeType": "branch-push",
      "major": {
        "automerge": false
      }
    }
  },
```

Then:
```
    "js-lib": {
      "description": "Default configuration for libraries",
      "extends": [
        "config:base",
        ":pinOnlyDevDependencies"
      ]
    },
```

Then:
```
    "pinOnlyDevDependencies": {
      "description": "Pin dependency versions for <code>devDependencies</code> and retain semver ranges for others",
      "packageRules": [
        {
          "packagePatterns": [
            "*"
          ],
          "rangeStrategy": "auto"
        },
        {
          "depTypeList": [
            "devDependencies"
          ],
          "rangeStrategy": "pin"
        }
      ]
    },
```

**Comment by rarkins** [comment]
I published a new preset for now that sets that rangeStrategy to be "replace" rather than "auto". But I'd like to work out why Renovate incorrectly detects this lib is an app.

**Comment by ryasmi** [comment]
No worries Rhys 👍 Thanks for the PR, I'll get that merged now. I'm also going to post a link to the docs here in case anyone else comes to this issue wondering what effect "replace" has on the behaviour.

https://renovatebot.com/docs/configuration-options/#rangestrategy

**Comment by rarkins** [comment]
The reason it's detected as an app is that there's no `main` present. But that still shouldn't be a concern if you've explicitly specified it's a library presets, so I will retain the preset change permanently to explicitly set rangeStrategy to "replace" for libs. Sorry again for the inconvenience.

**Comment by ryasmi** [comment]
Ah okay. Ok no worries, thanks for the quick help as always 👍
