### ISSUE TITLE
Show: Grouping of unit test related javascript dependencies

### ISSUE THREAD

**Issue by voxpelli** [renovatebot/presets#57]
I created a preset of my own to enable me to group unit test related packages just like linter-packages can be grouped through the official presets.

The configuration can be found here: https://github.com/voxpelli/renovate-config-voxpelli/blob/master/package.json

An example of a PR can be found here: https://github.com/voxpelli/node-jekyll-utils/pull/13

I have made no attempt to list all unit test related javascript packages, but rather listed the one I know I use across my projects

**Update:** Feel free to include these among the other official groups you have in here if you like 🙂

**Comment by rarkins** [comment]
Thanks @voxpelli, I think combining unit test packages is a good idea, also because they are perfect candidates for automerging (if the PR passes tests, few people are really going to dig into release notes first before manually merging).

**Comment by rarkins** [comment]
Maybe we start with the example you gave, e.g. with subgroups.

at top level, "test packages"
it consists of multiple test types below it, in case people want to apply separate rules:
- unit test packages
- integration test packages
- etc

**Comment by rarkins** [comment]
@voxpelli I've now merged this idea into the official presets. You might also be interested in the "non major" groups I added too. i.e. group updates together but only non-major ones - separate each major update into its own PR.

**Comment by voxpelli** [comment]
Thanks a lot @rarkins!
