### ISSUE TITLE
JSON Schema for validating configs

### ISSUE THREAD

**Issue by ahmadnassri** [renovatebot/presets#63]
would love to have a JSON schema (as an npm package) to use for validating our custom config as part of our build and release process.

the npm package should just expose the JSON schema itself, and users can adopt any JSON Schema testing tool to run the validation

**Comment by rarkins** [comment]
Hi @ahmadnassri, I have an issue open for this in the main repo, which is probably where we'd generate it from: https://github.com/renovateapp/renovate/issues/545

If you have some experience/expertise with JSON schema, I'd really appreciate some guidance to get it moving. I think we basically just need to translate from our existing `lib/config/definitions.js`.

**Comment by ahmadnassri** [comment]
excellent, I'll look there
