### ISSUE TITLE
Add grouping for angular.js monorepo

### ISSUE THREAD

**Issue by edmorley** [renovatebot/presets#7]
Hi!

I see there is grouping support for Angular (as in v2+):
https://github.com/singapore/renovate-config/blob/dbe6d310deeb47be1438a28394fcbc386ffa7171/packages/renovate-config-monorepo/package.json#L12-L15
https://github.com/singapore/renovate-config/blob/dbe6d310deeb47be1438a28394fcbc386ffa7171/packages/renovate-config-group/package.json#L19-L27
https://github.com/singapore/renovate-config/blob/dbe6d310deeb47be1438a28394fcbc386ffa7171/packages/renovate-config-group/package.json#L71

The mozilla/treeherder project (mozilla/treeherder#3025) still uses Angular.js (as in v1; 😭), which doesn't currently have grouping support enabled - though does have these package names defined:
https://github.com/singapore/renovate-config/blob/dbe6d310deeb47be1438a28394fcbc386ffa7171/packages/renovate-config-packages/package.json#L12-L20

Would there be any objection to enabling grouping for the packages listed here?
https://github.com/angular/angular.js/blob/master/scripts/bower/repos.inc
(which matches the names here: https://code.angularjs.org/1.6.6/)

**Comment by rarkins** [comment]
@edmorley this is done - see https://github.com/mozilla/treeherder/pull/3025

**Comment by edmorley** [comment]
Many thanks :-)
