### ISSUE TITLE
Add php/composer preset

### ISSUE THREAD

**Issue by alexander-akait** [renovatebot/presets#86]
Will be great :+1:

**Comment by rarkins** [comment]
Sorry, what specifically do you want it to do? Enable php/composer? 

Now that the hosted app has composer lockfile updating, maybe it should be enabled by default in the app anyway.

**Comment by alexander-akait** [comment]
@rarkins 

> Sorry, what specifically do you want it to do? Enable php/composer?

Yes. Example:
```
{
  "extends": ["config:base", ":composer"]
}
```

> Now that the hosted app has composer lockfile updating, maybe it should be enabled by default in the app anyway.

Maybe you are right, will be great have zero configuration for projects.

**Comment by rarkins** [comment]
composer is now enabled by default
