### ISSUE TITLE
Add groupings for Java Hibernate monorepo

### ISSUE THREAD

**Issue by ChristianMurphy** [renovatebot/presets#91]
Hibernate is a Java framework available through Maven Central on Maven and Gradle.
http://hibernate.org
https://mvnrepository.com/artifact/org.hibernate

Hibernate has several groupings

| name | group | example |
|-|-|-|
| Hibernate Core | `org.hibernate` | `org.hibernate:hibernate-tools` |
| Hibernate Validator | `org.hibernate.validator` | `org.hibernate.validator:hibernate-validator-osgi` |
| Hibernate OGM | `org.hibernate.ogm` | `org.hibernate.ogm:hibernate-ogm-mongodb` |
| Hibernate Commons | `org.hibernate.common` | `org.hibernate.common:hibernate-commons-annotations` |

**Comment by rarkins** [comment]
Should these all be separate groups, or all of the above combined into one PR?

**Comment by ChristianMurphy** [comment]
These are each separate monorepo groups.
