### ISSUE TITLE
Add socket.io monorepo

### ISSUE THREAD

**Issue by xPaw** [renovatebot/presets#94]
`socket.io` and `socket.io-client` would be main offenders, they share version number and release at the same time. I'm unsure if other socket.io repos can also apply.

**Comment by rarkins** [comment]
It's not technically a "monorepo" because they come from different github repos. I've defined a new "group:socketio" for all packages matching `^socket.io`, included that in "group:recommended", which is included into "config:base".

**Comment by xPaw** [comment]
> It's not technically a "monorepo" because they come from different github repos. 

That's true, but for the end user it kinda doesn't matter.

Thank you!
