### ISSUE TITLE
feat: add angular cli monorepo

### ISSUE THREAD

**Issue by viceice** [renovatebot/presets#99]
Should angular cli be a monorepo? The release several packages from the [cli repo](https://github.com/angular/angular-cli#packages).

**Comment by rarkins** [comment]
Sure, but let's start using [sourceUrlPrefixes](https://renovatebot.com/docs/configuration-options/#sourceurlprefixes) to simplify the rule here.

**Comment by viceice** [comment]
Is it possible to add packagerules to the selfhosted renovate config? I tried that, i don't want to build an extra npm package.

**Comment by viceice** [comment]
I'll send a pr.

**Comment by viceice** [comment]
> Sure, but let's start using [sourceUrlPrefixes](https://renovatebot.com/docs/configuration-options/#sourceurlprefixes) to simplify the rule here.

Should we refactor existing mono repos where possible?

**Comment by rarkins** [comment]
> Should we refactor existing mono repos where possible?

Yes but it's essentially a breaking change for anyone who's using a version of Renovate prior to when `sourceUrlPrefixes` was added. Mainly, I need to make sure all self-hosted Renovate Pro users have updated to the latest first.

**Comment by viceice** [comment]
Ok, maybe we should add an anouncement (pinned issue) to the renovate repo?

Maybe we should add a version contraint to the renovate cli, that pin's the major version of the renovate core presets?

**Comment by rarkins** [comment]
In general with an open source tool, users need to keep updated anyway (especially a tool whose purpose is updating..). I prefer not to confuse the majority of users with any pinned message only applicable to a small percentage of users who would be unlikely to see the message anyway.

The impact is that the existing "automatic" grouping would stop working, so it's not like the tool itself stops working. It's already been "months" so should be safe enough to do soon once Pro users are all updated (they tend to stay behind for stability reasons and I support them in that).
